# Generated by Django 2.0.13 on 2019-03-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0033_auto_20190301_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enkelvoudiginformatieobject',
            options={},
        ),
        migrations.AddField(
            model_name='enkelvoudiginformatieobject',
            name='_object_id',
            field=models.TextField(blank=True, help_text='CMIS storage object id, internal use only'),
        ),
    ]
