language: python
python:
  - 3.6

services:
  - docker

install:
  - docker build -t latest .
  - docker push scrumteamzgw/gemma-documentregistratiecomponent:latest

# safelist
branches:
  only:
  - master
  # TODO: This should be removed.
  - feature/build-cmis
