# Generated by Django 2.0.13 on 2019-04-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmis', '0002_drccmisconnection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drccmisconnection',
            old_name='_object_id',
            new_name='cmis_object_id',
        ),
    ]
